#ifndef PWM_CONFIG_H_
#define PWM_CONFIG_H_


/*PWM_FAST_PWM_MODE OR PWM_PHASE_CORRECT_MODE */
#define PWM_MODE PWM_FAST_PWM_MODE

/*PWM_CHANNEL_0 
PWM_CHANNEL_1_A 
PWM_CHANNEL_1_B
PWM_CHANNEL_1_AB
PWM_CHANNEL_2*/

#define PWM_CHANNEL PWM_CHANNEL_1_AB

/*PWM_PHASE_CORRECT_MODE OR PWM_FAST_PWM_MODE for TIMER 0 and TIMER 2

    The modes below for timer 0 only
    PWM_PHASE_CORRECT_8_BIT 1
    PWM_PHASE_CORRECT_9_BIT 2
    PWM_PHASE_CORRECT_10_BIT 3

    PWM_FAST_PWM_8_BIT 5
    PWM_FAST_PWM_9_BIT 6
    PWM_FAST_PWM_10_BIT 7
*/

#define PWM_PULSE_MODE PWM_FAST_PWM_10_BIT



/*PWM_EXTERNAL_CLK OR PWM_INTERNAL_CLK*/
#define PWM_CLK_SOURCE  PWM_CPU_CLK

#define PWM_PRESCALER PWM_PRESC_256

/*
PWM_NON_INVERTING_MODE \ PWM_INVERTING_MODE*/
#define PWM_PHASE_MODE PWM_NON_INVERTING_MODE













#endif // !PWM_CONFIG_H_
